services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: fhmoscow
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U myuser -d fhmoscow' ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    command: sh -c "npm run migrate && npm run seed"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
    restart: 'no'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy